### ISSUE TITLE
An update for v10

### ISSUE THREAD

**Issue by FrontBrandon14** [DM-miX/scene-transitions#23]
It's not working properly anymore. I cant change the text anymore. It keeps putting my old text when i transition.

**Comment by Ironxxx** [comment]
While most of the settings do work, the module no longer seems to allow Text to be saved to a transition. So you can have an image show but the text refuses to save.
On opening a transition for Editing the following error pops up:
```
commons.js:1703 Error: The content option for the editor handlebars helper has been deprecated. Please pass the content in as the first option to the helper and ensure it has already been enriched by TextEditor.enrichHTML if necessary
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Object.editor (foundry.js:7038:21)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:33:145)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:6906:10)
    at async TransitionForm._renderInner (foundry.js:5230:16)
    at async TransitionForm._renderInner (foundry.js:5791:18)
    at async TransitionForm._render (foundry.js:5073:19)
    at async TransitionForm._render (foundry.js:5780:5)
```

On trying to save a transition, the following critical error pops up:
```
foundry.js:6018 Uncaught (in promise) Error: content is not an active editor name!
[Detected 1 package: scene-transitions]
    at TransitionForm.saveEditor (foundry.js:6018:46)
    at jR.save_onsavecallback (scene-transitions.js:486:44)
    at plugin.min.js:4:1197
    at jR.<anonymous> (plugin.min.js:4:1412)
    at commands.exec.<computed> (tinymce.min.js:4:358670)
    at iR.execCommand (tinymce.min.js:4:358116)
    at jR.execCommand (tinymce.min.js:4:383782)
    at Object.onAction (plugin.min.js:4:842)
    at theme.min.js:4:261255
    at theme.min.js:4:118394
    at theme.min.js:4:261224
    at theme.min.js:4:29516
    at N (theme.min.js:4:2455)
    at run (theme.min.js:4:29501)
    at theme.min.js:4:30368
    at theme.min.js:4:782
    at theme.min.js:4:139333
    at B.fold (theme.min.js:4:1075)
    at fx (theme.min.js:4:139241)
    at bx (theme.min.js:4:139633)
    at vx (theme.min.js:4:139720)
    at theme.min.js:4:141481
    at theme.min.js:4:37522
    at li (theme.min.js:4:38286)
    at Object.triggerEvent (theme.min.js:4:141470)
    at Cr (theme.min.js:4:25368)
    at xr (theme.min.js:4:25213)
    at Sr (theme.min.js:4:25276)
    at e (theme.min.js:4:86243)
    at theme.min.js:4:30368
    at theme.min.js:4:782
    at theme.min.js:4:139333
    at B.fold (theme.min.js:4:1075)
    at fx (theme.min.js:4:139241)
    at bx (theme.min.js:4:139633)
    at vx (theme.min.js:4:139720)
    at theme.min.js:4:141389
    at theme.min.js:4:141410
    at theme.min.js:4:37522
    at li (theme.min.js:4:38286)
    at Object.triggerEvent (theme.min.js:4:141359)
    at theme.min.js:4:138209
    at HTMLDivElement.<anonymous> (theme.min.js:4:13954)
```

**Comment by coffiarts** [comment]
I have the impression that this has been fixed in v11. At least saving text works fine for me (but it has also worked for me in v10).
Apart from that, I've found at least one new issue in v11. See https://github.com/DM-miX/scene-transitions/issues/24
